version: '3.7'
services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/nuclear
    working_dir: /nuclear
    command: bash -xc "
      npx lerna exec npm rebuild node-sass;
      npx lerna run start "
    devices:
      - "/dev/snd"
    environment:
      - DISPLAY
      - HOME
    network_mode: host
    ipc: host  