version: '3.7'
services:

  install:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
    - .:/nuclear
    command: bash -xc "
      cd /nuclear;
      npm install "

  dev:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    depends_on:
      - install
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/nuclear
    command: bash -xc "
      npm install;
      npm start  "
    devices:
      - "/dev/snd"
    environment:
      - DISPLAY
      - HOME
    network_mode: host
    ipc: host
