// flow-typed signature: fa8191a7d368098526645021a50ac0be
// flow-typed version: <<STUB>>/jquery_v^2.2.3/flow_v0.37.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jquery'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jquery' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jquery/dist/jquery' {
  declare module.exports: any;
}

declare module 'jquery/dist/jquery.min' {
  declare module.exports: any;
}

declare module 'jquery/external/sizzle/dist/sizzle' {
  declare module.exports: any;
}

declare module 'jquery/external/sizzle/dist/sizzle.min' {
  declare module.exports: any;
}

declare module 'jquery/src/ajax' {
  declare module.exports: any;
}

declare module 'jquery/src/ajax/jsonp' {
  declare module.exports: any;
}

declare module 'jquery/src/ajax/load' {
  declare module.exports: any;
}

declare module 'jquery/src/ajax/parseJSON' {
  declare module.exports: any;
}

declare module 'jquery/src/ajax/parseXML' {
  declare module.exports: any;
}

declare module 'jquery/src/ajax/script' {
  declare module.exports: any;
}

declare module 'jquery/src/ajax/var/location' {
  declare module.exports: any;
}

declare module 'jquery/src/ajax/var/nonce' {
  declare module.exports: any;
}

declare module 'jquery/src/ajax/var/rquery' {
  declare module.exports: any;
}

declare module 'jquery/src/ajax/xhr' {
  declare module.exports: any;
}

declare module 'jquery/src/attributes' {
  declare module.exports: any;
}

declare module 'jquery/src/attributes/attr' {
  declare module.exports: any;
}

declare module 'jquery/src/attributes/classes' {
  declare module.exports: any;
}

declare module 'jquery/src/attributes/prop' {
  declare module.exports: any;
}

declare module 'jquery/src/attributes/support' {
  declare module.exports: any;
}

declare module 'jquery/src/attributes/val' {
  declare module.exports: any;
}

declare module 'jquery/src/callbacks' {
  declare module.exports: any;
}

declare module 'jquery/src/core' {
  declare module.exports: any;
}

declare module 'jquery/src/core/access' {
  declare module.exports: any;
}

declare module 'jquery/src/core/init' {
  declare module.exports: any;
}

declare module 'jquery/src/core/parseHTML' {
  declare module.exports: any;
}

declare module 'jquery/src/core/ready' {
  declare module.exports: any;
}

declare module 'jquery/src/core/var/rsingleTag' {
  declare module.exports: any;
}

declare module 'jquery/src/css' {
  declare module.exports: any;
}

declare module 'jquery/src/css/addGetHookIf' {
  declare module.exports: any;
}

declare module 'jquery/src/css/adjustCSS' {
  declare module.exports: any;
}

declare module 'jquery/src/css/curCSS' {
  declare module.exports: any;
}

declare module 'jquery/src/css/defaultDisplay' {
  declare module.exports: any;
}

declare module 'jquery/src/css/hiddenVisibleSelectors' {
  declare module.exports: any;
}

declare module 'jquery/src/css/showHide' {
  declare module.exports: any;
}

declare module 'jquery/src/css/support' {
  declare module.exports: any;
}

declare module 'jquery/src/css/var/cssExpand' {
  declare module.exports: any;
}

declare module 'jquery/src/css/var/getStyles' {
  declare module.exports: any;
}

declare module 'jquery/src/css/var/isHidden' {
  declare module.exports: any;
}

declare module 'jquery/src/css/var/rmargin' {
  declare module.exports: any;
}

declare module 'jquery/src/css/var/rnumnonpx' {
  declare module.exports: any;
}

declare module 'jquery/src/css/var/swap' {
  declare module.exports: any;
}

declare module 'jquery/src/data' {
  declare module.exports: any;
}

declare module 'jquery/src/data/Data' {
  declare module.exports: any;
}

declare module 'jquery/src/data/var/acceptData' {
  declare module.exports: any;
}

declare module 'jquery/src/data/var/dataPriv' {
  declare module.exports: any;
}

declare module 'jquery/src/data/var/dataUser' {
  declare module.exports: any;
}

declare module 'jquery/src/deferred' {
  declare module.exports: any;
}

declare module 'jquery/src/deprecated' {
  declare module.exports: any;
}

declare module 'jquery/src/dimensions' {
  declare module.exports: any;
}

declare module 'jquery/src/effects' {
  declare module.exports: any;
}

declare module 'jquery/src/effects/animatedSelector' {
  declare module.exports: any;
}

declare module 'jquery/src/effects/Tween' {
  declare module.exports: any;
}

declare module 'jquery/src/event' {
  declare module.exports: any;
}

declare module 'jquery/src/event/ajax' {
  declare module.exports: any;
}

declare module 'jquery/src/event/alias' {
  declare module.exports: any;
}

declare module 'jquery/src/event/focusin' {
  declare module.exports: any;
}

declare module 'jquery/src/event/support' {
  declare module.exports: any;
}

declare module 'jquery/src/event/trigger' {
  declare module.exports: any;
}

declare module 'jquery/src/exports/amd' {
  declare module.exports: any;
}

declare module 'jquery/src/exports/global' {
  declare module.exports: any;
}

declare module 'jquery/src/intro' {
  declare module.exports: any;
}

declare module 'jquery/src/jquery' {
  declare module.exports: any;
}

declare module 'jquery/src/manipulation' {
  declare module.exports: any;
}

declare module 'jquery/src/manipulation/_evalUrl' {
  declare module.exports: any;
}

declare module 'jquery/src/manipulation/buildFragment' {
  declare module.exports: any;
}

declare module 'jquery/src/manipulation/getAll' {
  declare module.exports: any;
}

declare module 'jquery/src/manipulation/setGlobalEval' {
  declare module.exports: any;
}

declare module 'jquery/src/manipulation/support' {
  declare module.exports: any;
}

declare module 'jquery/src/manipulation/var/rcheckableType' {
  declare module.exports: any;
}

declare module 'jquery/src/manipulation/var/rscriptType' {
  declare module.exports: any;
}

declare module 'jquery/src/manipulation/var/rtagName' {
  declare module.exports: any;
}

declare module 'jquery/src/manipulation/wrapMap' {
  declare module.exports: any;
}

declare module 'jquery/src/offset' {
  declare module.exports: any;
}

declare module 'jquery/src/outro' {
  declare module.exports: any;
}

declare module 'jquery/src/queue' {
  declare module.exports: any;
}

declare module 'jquery/src/queue/delay' {
  declare module.exports: any;
}

declare module 'jquery/src/selector-native' {
  declare module.exports: any;
}

declare module 'jquery/src/selector-sizzle' {
  declare module.exports: any;
}

declare module 'jquery/src/selector' {
  declare module.exports: any;
}

declare module 'jquery/src/serialize' {
  declare module.exports: any;
}

declare module 'jquery/src/traversing' {
  declare module.exports: any;
}

declare module 'jquery/src/traversing/findFilter' {
  declare module.exports: any;
}

declare module 'jquery/src/traversing/var/dir' {
  declare module.exports: any;
}

declare module 'jquery/src/traversing/var/rneedsContext' {
  declare module.exports: any;
}

declare module 'jquery/src/traversing/var/siblings' {
  declare module.exports: any;
}

declare module 'jquery/src/var/arr' {
  declare module.exports: any;
}

declare module 'jquery/src/var/class2type' {
  declare module.exports: any;
}

declare module 'jquery/src/var/concat' {
  declare module.exports: any;
}

declare module 'jquery/src/var/document' {
  declare module.exports: any;
}

declare module 'jquery/src/var/documentElement' {
  declare module.exports: any;
}

declare module 'jquery/src/var/hasOwn' {
  declare module.exports: any;
}

declare module 'jquery/src/var/indexOf' {
  declare module.exports: any;
}

declare module 'jquery/src/var/pnum' {
  declare module.exports: any;
}

declare module 'jquery/src/var/push' {
  declare module.exports: any;
}

declare module 'jquery/src/var/rcssNum' {
  declare module.exports: any;
}

declare module 'jquery/src/var/rnotwhite' {
  declare module.exports: any;
}

declare module 'jquery/src/var/slice' {
  declare module.exports: any;
}

declare module 'jquery/src/var/support' {
  declare module.exports: any;
}

declare module 'jquery/src/var/toString' {
  declare module.exports: any;
}

declare module 'jquery/src/wrap' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jquery/dist/jquery.js' {
  declare module.exports: $Exports<'jquery/dist/jquery'>;
}
declare module 'jquery/dist/jquery.min.js' {
  declare module.exports: $Exports<'jquery/dist/jquery.min'>;
}
declare module 'jquery/external/sizzle/dist/sizzle.js' {
  declare module.exports: $Exports<'jquery/external/sizzle/dist/sizzle'>;
}
declare module 'jquery/external/sizzle/dist/sizzle.min.js' {
  declare module.exports: $Exports<'jquery/external/sizzle/dist/sizzle.min'>;
}
declare module 'jquery/src/ajax.js' {
  declare module.exports: $Exports<'jquery/src/ajax'>;
}
declare module 'jquery/src/ajax/jsonp.js' {
  declare module.exports: $Exports<'jquery/src/ajax/jsonp'>;
}
declare module 'jquery/src/ajax/load.js' {
  declare module.exports: $Exports<'jquery/src/ajax/load'>;
}
declare module 'jquery/src/ajax/parseJSON.js' {
  declare module.exports: $Exports<'jquery/src/ajax/parseJSON'>;
}
declare module 'jquery/src/ajax/parseXML.js' {
  declare module.exports: $Exports<'jquery/src/ajax/parseXML'>;
}
declare module 'jquery/src/ajax/script.js' {
  declare module.exports: $Exports<'jquery/src/ajax/script'>;
}
declare module 'jquery/src/ajax/var/location.js' {
  declare module.exports: $Exports<'jquery/src/ajax/var/location'>;
}
declare module 'jquery/src/ajax/var/nonce.js' {
  declare module.exports: $Exports<'jquery/src/ajax/var/nonce'>;
}
declare module 'jquery/src/ajax/var/rquery.js' {
  declare module.exports: $Exports<'jquery/src/ajax/var/rquery'>;
}
declare module 'jquery/src/ajax/xhr.js' {
  declare module.exports: $Exports<'jquery/src/ajax/xhr'>;
}
declare module 'jquery/src/attributes.js' {
  declare module.exports: $Exports<'jquery/src/attributes'>;
}
declare module 'jquery/src/attributes/attr.js' {
  declare module.exports: $Exports<'jquery/src/attributes/attr'>;
}
declare module 'jquery/src/attributes/classes.js' {
  declare module.exports: $Exports<'jquery/src/attributes/classes'>;
}
declare module 'jquery/src/attributes/prop.js' {
  declare module.exports: $Exports<'jquery/src/attributes/prop'>;
}
declare module 'jquery/src/attributes/support.js' {
  declare module.exports: $Exports<'jquery/src/attributes/support'>;
}
declare module 'jquery/src/attributes/val.js' {
  declare module.exports: $Exports<'jquery/src/attributes/val'>;
}
declare module 'jquery/src/callbacks.js' {
  declare module.exports: $Exports<'jquery/src/callbacks'>;
}
declare module 'jquery/src/core.js' {
  declare module.exports: $Exports<'jquery/src/core'>;
}
declare module 'jquery/src/core/access.js' {
  declare module.exports: $Exports<'jquery/src/core/access'>;
}
declare module 'jquery/src/core/init.js' {
  declare module.exports: $Exports<'jquery/src/core/init'>;
}
declare module 'jquery/src/core/parseHTML.js' {
  declare module.exports: $Exports<'jquery/src/core/parseHTML'>;
}
declare module 'jquery/src/core/ready.js' {
  declare module.exports: $Exports<'jquery/src/core/ready'>;
}
declare module 'jquery/src/core/var/rsingleTag.js' {
  declare module.exports: $Exports<'jquery/src/core/var/rsingleTag'>;
}
declare module 'jquery/src/css.js' {
  declare module.exports: $Exports<'jquery/src/css'>;
}
declare module 'jquery/src/css/addGetHookIf.js' {
  declare module.exports: $Exports<'jquery/src/css/addGetHookIf'>;
}
declare module 'jquery/src/css/adjustCSS.js' {
  declare module.exports: $Exports<'jquery/src/css/adjustCSS'>;
}
declare module 'jquery/src/css/curCSS.js' {
  declare module.exports: $Exports<'jquery/src/css/curCSS'>;
}
declare module 'jquery/src/css/defaultDisplay.js' {
  declare module.exports: $Exports<'jquery/src/css/defaultDisplay'>;
}
declare module 'jquery/src/css/hiddenVisibleSelectors.js' {
  declare module.exports: $Exports<'jquery/src/css/hiddenVisibleSelectors'>;
}
declare module 'jquery/src/css/showHide.js' {
  declare module.exports: $Exports<'jquery/src/css/showHide'>;
}
declare module 'jquery/src/css/support.js' {
  declare module.exports: $Exports<'jquery/src/css/support'>;
}
declare module 'jquery/src/css/var/cssExpand.js' {
  declare module.exports: $Exports<'jquery/src/css/var/cssExpand'>;
}
declare module 'jquery/src/css/var/getStyles.js' {
  declare module.exports: $Exports<'jquery/src/css/var/getStyles'>;
}
declare module 'jquery/src/css/var/isHidden.js' {
  declare module.exports: $Exports<'jquery/src/css/var/isHidden'>;
}
declare module 'jquery/src/css/var/rmargin.js' {
  declare module.exports: $Exports<'jquery/src/css/var/rmargin'>;
}
declare module 'jquery/src/css/var/rnumnonpx.js' {
  declare module.exports: $Exports<'jquery/src/css/var/rnumnonpx'>;
}
declare module 'jquery/src/css/var/swap.js' {
  declare module.exports: $Exports<'jquery/src/css/var/swap'>;
}
declare module 'jquery/src/data.js' {
  declare module.exports: $Exports<'jquery/src/data'>;
}
declare module 'jquery/src/data/Data.js' {
  declare module.exports: $Exports<'jquery/src/data/Data'>;
}
declare module 'jquery/src/data/var/acceptData.js' {
  declare module.exports: $Exports<'jquery/src/data/var/acceptData'>;
}
declare module 'jquery/src/data/var/dataPriv.js' {
  declare module.exports: $Exports<'jquery/src/data/var/dataPriv'>;
}
declare module 'jquery/src/data/var/dataUser.js' {
  declare module.exports: $Exports<'jquery/src/data/var/dataUser'>;
}
declare module 'jquery/src/deferred.js' {
  declare module.exports: $Exports<'jquery/src/deferred'>;
}
declare module 'jquery/src/deprecated.js' {
  declare module.exports: $Exports<'jquery/src/deprecated'>;
}
declare module 'jquery/src/dimensions.js' {
  declare module.exports: $Exports<'jquery/src/dimensions'>;
}
declare module 'jquery/src/effects.js' {
  declare module.exports: $Exports<'jquery/src/effects'>;
}
declare module 'jquery/src/effects/animatedSelector.js' {
  declare module.exports: $Exports<'jquery/src/effects/animatedSelector'>;
}
declare module 'jquery/src/effects/Tween.js' {
  declare module.exports: $Exports<'jquery/src/effects/Tween'>;
}
declare module 'jquery/src/event.js' {
  declare module.exports: $Exports<'jquery/src/event'>;
}
declare module 'jquery/src/event/ajax.js' {
  declare module.exports: $Exports<'jquery/src/event/ajax'>;
}
declare module 'jquery/src/event/alias.js' {
  declare module.exports: $Exports<'jquery/src/event/alias'>;
}
declare module 'jquery/src/event/focusin.js' {
  declare module.exports: $Exports<'jquery/src/event/focusin'>;
}
declare module 'jquery/src/event/support.js' {
  declare module.exports: $Exports<'jquery/src/event/support'>;
}
declare module 'jquery/src/event/trigger.js' {
  declare module.exports: $Exports<'jquery/src/event/trigger'>;
}
declare module 'jquery/src/exports/amd.js' {
  declare module.exports: $Exports<'jquery/src/exports/amd'>;
}
declare module 'jquery/src/exports/global.js' {
  declare module.exports: $Exports<'jquery/src/exports/global'>;
}
declare module 'jquery/src/intro.js' {
  declare module.exports: $Exports<'jquery/src/intro'>;
}
declare module 'jquery/src/jquery.js' {
  declare module.exports: $Exports<'jquery/src/jquery'>;
}
declare module 'jquery/src/manipulation.js' {
  declare module.exports: $Exports<'jquery/src/manipulation'>;
}
declare module 'jquery/src/manipulation/_evalUrl.js' {
  declare module.exports: $Exports<'jquery/src/manipulation/_evalUrl'>;
}
declare module 'jquery/src/manipulation/buildFragment.js' {
  declare module.exports: $Exports<'jquery/src/manipulation/buildFragment'>;
}
declare module 'jquery/src/manipulation/getAll.js' {
  declare module.exports: $Exports<'jquery/src/manipulation/getAll'>;
}
declare module 'jquery/src/manipulation/setGlobalEval.js' {
  declare module.exports: $Exports<'jquery/src/manipulation/setGlobalEval'>;
}
declare module 'jquery/src/manipulation/support.js' {
  declare module.exports: $Exports<'jquery/src/manipulation/support'>;
}
declare module 'jquery/src/manipulation/var/rcheckableType.js' {
  declare module.exports: $Exports<'jquery/src/manipulation/var/rcheckableType'>;
}
declare module 'jquery/src/manipulation/var/rscriptType.js' {
  declare module.exports: $Exports<'jquery/src/manipulation/var/rscriptType'>;
}
declare module 'jquery/src/manipulation/var/rtagName.js' {
  declare module.exports: $Exports<'jquery/src/manipulation/var/rtagName'>;
}
declare module 'jquery/src/manipulation/wrapMap.js' {
  declare module.exports: $Exports<'jquery/src/manipulation/wrapMap'>;
}
declare module 'jquery/src/offset.js' {
  declare module.exports: $Exports<'jquery/src/offset'>;
}
declare module 'jquery/src/outro.js' {
  declare module.exports: $Exports<'jquery/src/outro'>;
}
declare module 'jquery/src/queue.js' {
  declare module.exports: $Exports<'jquery/src/queue'>;
}
declare module 'jquery/src/queue/delay.js' {
  declare module.exports: $Exports<'jquery/src/queue/delay'>;
}
declare module 'jquery/src/selector-native.js' {
  declare module.exports: $Exports<'jquery/src/selector-native'>;
}
declare module 'jquery/src/selector-sizzle.js' {
  declare module.exports: $Exports<'jquery/src/selector-sizzle'>;
}
declare module 'jquery/src/selector.js' {
  declare module.exports: $Exports<'jquery/src/selector'>;
}
declare module 'jquery/src/serialize.js' {
  declare module.exports: $Exports<'jquery/src/serialize'>;
}
declare module 'jquery/src/traversing.js' {
  declare module.exports: $Exports<'jquery/src/traversing'>;
}
declare module 'jquery/src/traversing/findFilter.js' {
  declare module.exports: $Exports<'jquery/src/traversing/findFilter'>;
}
declare module 'jquery/src/traversing/var/dir.js' {
  declare module.exports: $Exports<'jquery/src/traversing/var/dir'>;
}
declare module 'jquery/src/traversing/var/rneedsContext.js' {
  declare module.exports: $Exports<'jquery/src/traversing/var/rneedsContext'>;
}
declare module 'jquery/src/traversing/var/siblings.js' {
  declare module.exports: $Exports<'jquery/src/traversing/var/siblings'>;
}
declare module 'jquery/src/var/arr.js' {
  declare module.exports: $Exports<'jquery/src/var/arr'>;
}
declare module 'jquery/src/var/class2type.js' {
  declare module.exports: $Exports<'jquery/src/var/class2type'>;
}
declare module 'jquery/src/var/concat.js' {
  declare module.exports: $Exports<'jquery/src/var/concat'>;
}
declare module 'jquery/src/var/document.js' {
  declare module.exports: $Exports<'jquery/src/var/document'>;
}
declare module 'jquery/src/var/documentElement.js' {
  declare module.exports: $Exports<'jquery/src/var/documentElement'>;
}
declare module 'jquery/src/var/hasOwn.js' {
  declare module.exports: $Exports<'jquery/src/var/hasOwn'>;
}
declare module 'jquery/src/var/indexOf.js' {
  declare module.exports: $Exports<'jquery/src/var/indexOf'>;
}
declare module 'jquery/src/var/pnum.js' {
  declare module.exports: $Exports<'jquery/src/var/pnum'>;
}
declare module 'jquery/src/var/push.js' {
  declare module.exports: $Exports<'jquery/src/var/push'>;
}
declare module 'jquery/src/var/rcssNum.js' {
  declare module.exports: $Exports<'jquery/src/var/rcssNum'>;
}
declare module 'jquery/src/var/rnotwhite.js' {
  declare module.exports: $Exports<'jquery/src/var/rnotwhite'>;
}
declare module 'jquery/src/var/slice.js' {
  declare module.exports: $Exports<'jquery/src/var/slice'>;
}
declare module 'jquery/src/var/support.js' {
  declare module.exports: $Exports<'jquery/src/var/support'>;
}
declare module 'jquery/src/var/toString.js' {
  declare module.exports: $Exports<'jquery/src/var/toString'>;
}
declare module 'jquery/src/wrap.js' {
  declare module.exports: $Exports<'jquery/src/wrap'>;
}
