// flow-typed signature: 06362920641000ce2047bb0f1703a643
// flow-typed version: <<STUB>>/react-alert_v^1.0.14/flow_v0.37.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-alert'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-alert' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-alert/dev/components/AlertContainer' {
  declare module.exports: any;
}

declare module 'react-alert/dev/components/AlertMessage' {
  declare module.exports: any;
}

declare module 'react-alert/dist/alert' {
  declare module.exports: any;
}

declare module 'react-alert/tests/AlertContainerTest' {
  declare module.exports: any;
}

declare module 'react-alert/tests/AlertMessageTest' {
  declare module.exports: any;
}

declare module 'react-alert/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-alert/dev/components/AlertContainer.js' {
  declare module.exports: $Exports<'react-alert/dev/components/AlertContainer'>;
}
declare module 'react-alert/dev/components/AlertMessage.js' {
  declare module.exports: $Exports<'react-alert/dev/components/AlertMessage'>;
}
declare module 'react-alert/dist/alert.js' {
  declare module.exports: $Exports<'react-alert/dist/alert'>;
}
declare module 'react-alert/index' {
  declare module.exports: $Exports<'react-alert'>;
}
declare module 'react-alert/index.js' {
  declare module.exports: $Exports<'react-alert'>;
}
declare module 'react-alert/tests/AlertContainerTest.js' {
  declare module.exports: $Exports<'react-alert/tests/AlertContainerTest'>;
}
declare module 'react-alert/tests/AlertMessageTest.js' {
  declare module.exports: $Exports<'react-alert/tests/AlertMessageTest'>;
}
declare module 'react-alert/webpack.config.js' {
  declare module.exports: $Exports<'react-alert/webpack.config'>;
}
