// flow-typed signature: 5d1f603e7f4c4b7d9e31d8b2efcc1d69
// flow-typed version: <<STUB>>/react-sidebar_v^2.2.1/flow_v0.37.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-sidebar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-sidebar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-sidebar/dist-modules/index' {
  declare module.exports: any;
}

declare module 'react-sidebar/dist-modules/sidebar' {
  declare module.exports: any;
}

declare module 'react-sidebar/example/src/index' {
  declare module.exports: any;
}

declare module 'react-sidebar/example/src/material_title_panel' {
  declare module.exports: any;
}

declare module 'react-sidebar/example/src/responsive_example' {
  declare module.exports: any;
}

declare module 'react-sidebar/example/src/sidebar_content' {
  declare module.exports: any;
}

declare module 'react-sidebar/src/index' {
  declare module.exports: any;
}

declare module 'react-sidebar/src/sidebar' {
  declare module.exports: any;
}

declare module 'react-sidebar/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-sidebar/dist-modules/index.js' {
  declare module.exports: $Exports<'react-sidebar/dist-modules/index'>;
}
declare module 'react-sidebar/dist-modules/sidebar.js' {
  declare module.exports: $Exports<'react-sidebar/dist-modules/sidebar'>;
}
declare module 'react-sidebar/example/src/index.js' {
  declare module.exports: $Exports<'react-sidebar/example/src/index'>;
}
declare module 'react-sidebar/example/src/material_title_panel.js' {
  declare module.exports: $Exports<'react-sidebar/example/src/material_title_panel'>;
}
declare module 'react-sidebar/example/src/responsive_example.js' {
  declare module.exports: $Exports<'react-sidebar/example/src/responsive_example'>;
}
declare module 'react-sidebar/example/src/sidebar_content.js' {
  declare module.exports: $Exports<'react-sidebar/example/src/sidebar_content'>;
}
declare module 'react-sidebar/src/index.js' {
  declare module.exports: $Exports<'react-sidebar/src/index'>;
}
declare module 'react-sidebar/src/sidebar.js' {
  declare module.exports: $Exports<'react-sidebar/src/sidebar'>;
}
declare module 'react-sidebar/webpack.config.js' {
  declare module.exports: $Exports<'react-sidebar/webpack.config'>;
}
