// flow-typed signature: 83c0df2164d0d87e1095c8d3a85ecd8c
// flow-typed version: <<STUB>>/react-sound_v^0.4.0/flow_v0.37.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-sound'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-sound' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-sound/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-sound/lib/index.js' {
  declare module.exports: $Exports<'react-sound/lib/index'>;
}
