// flow-typed signature: abeed3b9e5714d547273c57d40555783
// flow-typed version: <<STUB>>/react-bootstrap-multiselect_v^2.3.0/flow_v0.37.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-bootstrap-multiselect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-bootstrap-multiselect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-bootstrap-multiselect/gulpfile' {
  declare module.exports: any;
}

declare module 'react-bootstrap-multiselect/lib/bootstrap-dropdown' {
  declare module.exports: any;
}

declare module 'react-bootstrap-multiselect/lib/bootstrap-multiselect-original' {
  declare module.exports: any;
}

declare module 'react-bootstrap-multiselect/lib/bootstrap-multiselect' {
  declare module.exports: any;
}

declare module 'react-bootstrap-multiselect/lib/get-options' {
  declare module.exports: any;
}

declare module 'react-bootstrap-multiselect/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-bootstrap-multiselect/gulpfile.js' {
  declare module.exports: $Exports<'react-bootstrap-multiselect/gulpfile'>;
}
declare module 'react-bootstrap-multiselect/lib/bootstrap-dropdown.js' {
  declare module.exports: $Exports<'react-bootstrap-multiselect/lib/bootstrap-dropdown'>;
}
declare module 'react-bootstrap-multiselect/lib/bootstrap-multiselect-original.js' {
  declare module.exports: $Exports<'react-bootstrap-multiselect/lib/bootstrap-multiselect-original'>;
}
declare module 'react-bootstrap-multiselect/lib/bootstrap-multiselect.js' {
  declare module.exports: $Exports<'react-bootstrap-multiselect/lib/bootstrap-multiselect'>;
}
declare module 'react-bootstrap-multiselect/lib/get-options.js' {
  declare module.exports: $Exports<'react-bootstrap-multiselect/lib/get-options'>;
}
declare module 'react-bootstrap-multiselect/lib/index.js' {
  declare module.exports: $Exports<'react-bootstrap-multiselect/lib/index'>;
}
