// flow-typed signature: 4706d008f946d322b5bf8bae53c58b80
// flow-typed version: <<STUB>>/soundmanager2_v^2.97.20150601-a/flow_v0.37.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'soundmanager2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'soundmanager2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'soundmanager2/script/soundmanager2-jsmin' {
  declare module.exports: any;
}

declare module 'soundmanager2/script/soundmanager2-nodebug-jsmin' {
  declare module.exports: any;
}

declare module 'soundmanager2/script/soundmanager2-nodebug' {
  declare module.exports: any;
}

declare module 'soundmanager2/script/soundmanager2' {
  declare module.exports: any;
}

// Filename aliases
declare module 'soundmanager2/script/soundmanager2-jsmin.js' {
  declare module.exports: $Exports<'soundmanager2/script/soundmanager2-jsmin'>;
}
declare module 'soundmanager2/script/soundmanager2-nodebug-jsmin.js' {
  declare module.exports: $Exports<'soundmanager2/script/soundmanager2-nodebug-jsmin'>;
}
declare module 'soundmanager2/script/soundmanager2-nodebug.js' {
  declare module.exports: $Exports<'soundmanager2/script/soundmanager2-nodebug'>;
}
declare module 'soundmanager2/script/soundmanager2.js' {
  declare module.exports: $Exports<'soundmanager2/script/soundmanager2'>;
}
