// flow-typed signature: 0695be6f1904a58d546c1a4c1fb8c5e0
// flow-typed version: <<STUB>>/youtube-dl_v^1.11.1/flow_v0.37.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'youtube-dl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'youtube-dl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'youtube-dl/example/audio' {
  declare module.exports: any;
}

declare module 'youtube-dl/example/download' {
  declare module.exports: any;
}

declare module 'youtube-dl/example/extractors' {
  declare module.exports: any;
}

declare module 'youtube-dl/example/formats' {
  declare module.exports: any;
}

declare module 'youtube-dl/example/info' {
  declare module.exports: any;
}

declare module 'youtube-dl/example/playlist' {
  declare module.exports: any;
}

declare module 'youtube-dl/example/resume' {
  declare module.exports: any;
}

declare module 'youtube-dl/lib/downloader' {
  declare module.exports: any;
}

declare module 'youtube-dl/lib/util' {
  declare module.exports: any;
}

declare module 'youtube-dl/lib/youtube-dl' {
  declare module.exports: any;
}

declare module 'youtube-dl/scripts/download' {
  declare module.exports: any;
}

declare module 'youtube-dl/test/download' {
  declare module.exports: any;
}

declare module 'youtube-dl/test/extractors' {
  declare module.exports: any;
}

declare module 'youtube-dl/test/getFormat' {
  declare module.exports: any;
}

declare module 'youtube-dl/test/getInfo' {
  declare module.exports: any;
}

declare module 'youtube-dl/test/playlist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'youtube-dl/example/audio.js' {
  declare module.exports: $Exports<'youtube-dl/example/audio'>;
}
declare module 'youtube-dl/example/download.js' {
  declare module.exports: $Exports<'youtube-dl/example/download'>;
}
declare module 'youtube-dl/example/extractors.js' {
  declare module.exports: $Exports<'youtube-dl/example/extractors'>;
}
declare module 'youtube-dl/example/formats.js' {
  declare module.exports: $Exports<'youtube-dl/example/formats'>;
}
declare module 'youtube-dl/example/info.js' {
  declare module.exports: $Exports<'youtube-dl/example/info'>;
}
declare module 'youtube-dl/example/playlist.js' {
  declare module.exports: $Exports<'youtube-dl/example/playlist'>;
}
declare module 'youtube-dl/example/resume.js' {
  declare module.exports: $Exports<'youtube-dl/example/resume'>;
}
declare module 'youtube-dl/lib/downloader.js' {
  declare module.exports: $Exports<'youtube-dl/lib/downloader'>;
}
declare module 'youtube-dl/lib/util.js' {
  declare module.exports: $Exports<'youtube-dl/lib/util'>;
}
declare module 'youtube-dl/lib/youtube-dl.js' {
  declare module.exports: $Exports<'youtube-dl/lib/youtube-dl'>;
}
declare module 'youtube-dl/scripts/download.js' {
  declare module.exports: $Exports<'youtube-dl/scripts/download'>;
}
declare module 'youtube-dl/test/download.js' {
  declare module.exports: $Exports<'youtube-dl/test/download'>;
}
declare module 'youtube-dl/test/extractors.js' {
  declare module.exports: $Exports<'youtube-dl/test/extractors'>;
}
declare module 'youtube-dl/test/getFormat.js' {
  declare module.exports: $Exports<'youtube-dl/test/getFormat'>;
}
declare module 'youtube-dl/test/getInfo.js' {
  declare module.exports: $Exports<'youtube-dl/test/getInfo'>;
}
declare module 'youtube-dl/test/playlist.js' {
  declare module.exports: $Exports<'youtube-dl/test/playlist'>;
}
