blank_issues_enabled: false
contact_links:
  - name: Contributing guidelines
    url: https://docs.nuclearplayer.com/nuclear/development/contributing
    about: Issues and PRs are not accepted. Please read the contribution guidelines above.
  - name: Translations
    url: https://crowdin.com/project/nuclear
    about: Translations can be contributed using Crowdin. Please do not open issues or PRs for translation changes.
