post_install () {
    ln -sf '/opt/nuclear/nuclear' '/usr/local/bin/nuclear'
}

pre_upgrade ()  {
    rm -rf /opt/nuclear
    rm -rf /usr/share/applications/nuclear.desktop
    rm -rf /usr/share/doc/nuclear
    rm -rf /usr/share/icons/hicolor/*/nuclear.png
    rm -rf /usr/local/bin/nuclear 
}

post_upgrade () {
    ln -sf '/opt/nuclear/nuclear' '/usr/local/bin/nuclear'
}

post_remove ()  {
    rm -rf /opt/nuclear
    rm -rf /usr/share/applications/nuclear.desktop
    rm -rf /usr/share/doc/nuclear
    rm -rf /usr/share/icons/hicolor/*/nuclear.png
    rm -rf /usr/local/bin/nuclear
}
