[package]
name = "scanner"
version = "0.1.0"
license = "AGPL-3.0"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
id3 = "1.7.0"

[dependencies.uuid]
version = "1.3.4"
features = [
    "v4",       
    "fast-rng"
]

[dependencies.neon]
version = "0.10"
default-features = false
features = ["napi-6"]
