[package]
name = "scanner"
version = "0.1.0"
license = "AGPL-3.0"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
id3 = "1.7.0"
md5 = "0.7.0"
mockall = "0.11.4"

[dependencies.image]
version = "0.24.7"
features = ["webp-encoder"]

[dependencies.uuid]
version = "1.3.4"
features = [
    "v4",       
    "fast-rng"
]

[dependencies.neon]
version = "0.10"
default-features = false
features = ["napi-6"]
