name: nuclear
base: core22
version: '${SNAP_VERSION}'
summary: Free music streaming app
description: |
  Nuclear is a free, open-source music player without ads or tracking.
  Search for any song or artist, build playlists, and start listening.

grade: stable
confinement: strict

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1

apps:
  nuclear:
    command: usr/bin/nuclear-music-player
    desktop: usr/share/applications/nuclear-music-player.desktop
    extensions: [gnome]
    environment:
      ALWAYS_USE_PULSEAUDIO: "1"
    plugs:
      - network
      - network-status
      - audio-playback
      - home
      - browser-support

package-repositories:
  - type: apt
    components: [main]
    suites: [jammy]
    key-id: 78E1918602959B9C59103100F1831DDAFC42E99D
    url: http://ppa.launchpad.net/snappy-dev/snapcraft-daily/ubuntu

parts:
  build-app:
    plugin: dump
    build-snaps:
      - node/22/stable
      - rustup/latest/stable
    build-packages:
      - libwebkit2gtk-4.1-dev
      - build-essential
      - curl
      - wget
      - file
      - libxdo-dev
      - libssl-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
      - dpkg
      - patchelf
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libayatana-appindicator3-1
    source: .
    override-build: |
      set -eu

      npm install -g pnpm
      pnpm install --frozen-lockfile

      cd packages/player
      pnpm tauri build --bundles deb

      dpkg -x src-tauri/target/release/bundle/deb/*.deb $SNAPCRAFT_PART_INSTALL/

      sed -i \
        "s|Icon=nuclear-music-player|Icon=/usr/share/icons/hicolor/32x32/apps/nuclear-music-player.png|g" \
        $SNAPCRAFT_PART_INSTALL/usr/share/applications/nuclear-music-player.desktop
