name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DO_NOT_TRACK: 1

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup JS
        uses: ./.github/actions/setup-js

      - name: Lint
        run: pnpm lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup JS
        uses: ./.github/actions/setup-js

      - name: Run tests with coverage
        run: pnpm test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./packages/*/coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./packages/*/test-results/junit.xml
          report_type: test_results
          name: codecov-test-results
          fail_ci_if_error: false

  build:
    runs-on: ubuntu-latest
    env:
      CARGO_PROFILE_DEV_DEBUG: 0

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: packages/player/src-tauri -> target

      - name: Install system dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev
          version: 1.0

      - name: Setup JS
        uses: ./.github/actions/setup-js

      - name: Build packages
        run: pnpm turbo build --filter='!@nuclearplayer/player'

      - name: Build player
        run: pnpm --filter @nuclearplayer/player tauri build --debug --no-bundle
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
